version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "DT-Dependabot"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "DT-Dependabot"
    groups:
      golang:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
